### ISSUE TITLE
More of a suggestion than an issue, but what about making comparators work with the obelisk?

### ISSUE THREAD

**Issue by myriantics** [EndLone/everlasting#1]
The mod is super cool,  but if comparators could read the obelisk then it would open up a lot of cool automation and integration possibilities.

**Comment by BackupCup** [comment]
The obelisk does work with comparators, however the comparator reads the amount of Sculk in the item slot. If you're referring to the comparator reading the Charge inside of the Obelisk, then probably no. You can think of Charge as kind of the same value as smelting progress of a furnace.
