### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by peow** [EndLone/everlasting#3]
Firstly, great mod

----------------------------
Suggestions: 

* Obelisk has a low sound that you can hear when you are very close to it, just like Beacon

* Have a sound effect to know when the Obelisk has become Overcharged

* A sound effect to know when the durability of all your Everlasting Capsules runs out, this would prevent, for example, someone from losing their gold pickaxe with efficiency V, thinking they still have the Capsule to protect its durability.

* A sound effect when you charge the Obelisk, something like a "tututu" when the Sculk Charge bar fills up inside the UI

If you add any of these suggestions please update to 1.20.1 with Fabric Loader 0.14.22 support, thank you

**Comment by BackupCup** [comment]
Thank you for your suggestions! They have been added in 1.3.0.

Everlasting _does_ support 0.14.22, however it relies on newer versions of Kotlin and Fabric API which require newer fabric versions.
