### ISSUE TITLE
the Restoring enchantment does not recognize XP given per command

### ISSUE THREAD

**Issue by peow** [EndLone/everlasting#4]
to reproduce:

 * get a item enchanted with Restoring
*/give @p minecraft:iron_shovel{Damage: 0, Enchantments: [{id: "everlasting:restoring", lvl: 1s}], RepairCost: 1}*

* use /xp to give yourself XP
*/xp add @p 10 levels*

* go to survival
*/gamemode survival*

* try to break blocks, you will see that your XP will not be consumed, and the item will lose durability

* try to get XP without commands, p.e using Experiencie Bottles
*/give @p minecraft:experience_bottle 5*

now the Restoring enchantment will work, however as soon as the XP you gained with the experience bottles runs out, the enchantment will no longer take effect, even if you still have 10 XP levels (given by the /xp command)

---------

im using Fabric 1.20.1, Everlasting v1.4.2

**Comment by BackupCup** [comment]
Thats normal behaviour. Restoring specifically ignores cheated xp, because it looks at the gained XP

**Comment by peow** [comment]
ok
